### ISSUE TITLE
Having multiple Groups causes one of them to hang

### ISSUE THREAD

**Issue by agomez08** [ni/niveristand-data-sharing-framework-custom-device#39]
**Describe the bug**

I have observed that after adding a certain number of groups (typically 4) one of them hangs. The group that hangs seems to be the last one in the configuration tree. 
My definition for "hang" in this situation is the next: The monitoring channels for the group do not change (i.e. frequency shows inf and iteration shows 0) and the group does not send or receive channels.
The log in /tmp/dsf.log does not report any related error.
Removing one of the other groups (and in some cases 2) causes the previously hung group to run just fine.
Using UDP plugin. I haven't had the chance to debug the source to identify if the problem is in the Core or in the UDP Plugin.

**To Reproduce**
I can share a .dsf file that reproduces the problem if needed. Here are the steps for a simple scenario that reproduces the problem:
1. Create 2 threads.
2. Add 2 groups to thread 0, one Tx and one Rx. 
3. Add one transfer to each group, and one channel to each thread.
4. Add 2 groups to thread 1, one Tx and one Rx. 
5. Add one transfer to each group, and one channel to each thread.
6. Configure IP addresses and network ports for the different items.
7. Deploy.
8. The last added group Monitoring channels hang and transfer is not communicating.

**Expected behavior**
I would guess that groups are not expected to hang, unless my configuration is wrong for some reason.

**Screenshots**

**Desktop (please complete the following information):**
 - LinuxRT-x64.
 - DSF 20.3.

**Additional context**

**Comment by rtzoeller** [comment]
It seems like the issue is caused specifically by having multiple groups in a thread. This also reproduces on Windows.
